export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGVtYWlsLmNvbSIsImlhdCI6MTY4ODk1MTIzMywiZXhwIjoxNjg5NTU2MDMzLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.Vt2CdrXkfOZPJM2tnXeya5ZslIT7UI7tXimLdrQTpCA';
